from pathlib import Path
from html import escape as e
import json
ROOT=Path(__file__).resolve().parent.parent
D=ROOT/'dist'
base='https://ciencias.bogota.unal.edu.co/'
OAN=base+'departamentos_e_Institutos/observatorio_astronomico_nacional/'
DIR=base+'directorio_docente/observatorio_astronomico_nacional/'
GROUP=base+'grupos_de_investigacion/astronomia/'
LAB=base+'laboratorios/observatorio_astronomico_nacional/'
SPEC='https://espectra.astronomiaoan.co/'
SOURCES={}
def link(url,label):return f'<a href="{e(url,quote=True)}" target="_blank" rel="noopener">{label} ↗</a>'
def source(url,label):
 SOURCES[url]=label
 return f'<p class="source-note">Fuente: {link(url,label)}.</p>'
def card(title,text,url=None,label='Conocer más',tag=None):
 return '<article class="card">'+(f'<span class="tag">{tag}</span>' if tag else '')+f'<h3>{title}</h3><p>{text}</p>'+(link(url,label) if url else '')+'</article>'
home=(D/'index.html').read_text()
HEAD=home[:home.index('<main')]
FOOT='''<footer id="footer"><div class="footer-grid"><div><h3>Observatorio<br>Astronómico Nacional</h3><p>Universidad Nacional de Colombia<br>Facultad de Ciencias · Sede Bogotá<br>Con los pies en la Tierra, la mirada en las estrellas.</p></div><div><h4>Explora</h4><a href="profesores.html">Profesores</a><a href="laboratorios.html">Laboratorios</a><a href="espectra.html">Revista eSPECTRA</a><a href="egresados.html">Egresados</a><a href="amigos.html">Amigos del Observatorio</a><a href="fuentes.html">Fuentes y créditos</a></div><div><h4>Hablemos</h4><a href="mailto:obsan_fcbog@unal.edu.co">obsan_fcbog@unal.edu.co</a><a href="mailto:serviciosoan_fcbog@unal.edu.co">serviciosoan_fcbog@unal.edu.co</a><p>Ciudad Universitaria · Edificio 413<br>Carrera 45 # 26-85, Bogotá<br>(+57 601) 316 5000, ext. 11021</p><a href="https://www.instagram.com/astronomiaoan" target="_blank" rel="noopener">Instagram ↗</a><a href="https://www.youtube.com/channel/UCb1rF7m6wUC4Zhw-zsUWvLA" target="_blank" rel="noopener">YouTube del OAN ↗</a></div></div><div class="footer-bottom"><span>Propuesta de portal · Información consultada el 16 de septiembre de 2026.</span><span><a href="https://ciencias.bogota.unal.edu.co/departamentos_e_Institutos/observatorio_astronomico_nacional/">Consultar el sitio institucional ↗</a></span></div></footer>'''
(D/'index.html').write_text(home.replace('<footer id="footer"></footer>',FOOT))
def page(file,title,kicker,intro,body,nav=[]):
 head=HEAD.replace('<title>Observatorio Astronómico Nacional · Colombia</title>',f'<title>{title} · OAN Colombia</title>')
 sub='<div class="subnav">'+''.join(f'<a href="#{a}">{b}</a>' for a,b in nav)+'</div>' if nav else ''
 s=head+f'<main id="contenido"><div class="page-hero"><div class="breadcrumb"><a href="index.html">Inicio</a> / {title}</div><p class="eyebrow">{kicker}</p><h1>{title}</h1><p>{intro}</p></div>'+sub+'<div class="content">'+body+'</div></main>'+FOOT+'</body></html>'
 (D/(file+'.html')).write_text(s)
def section(id,title,text):return f'<section id="{id}"><h2>{title}</h2>{text}</section>'

ma=base+'estudiar_en_la_facultad/posgrados/maestrias/astronomia/'
area=base+'areas_curriculares/astronomia/'
academia=section('programas','Formación para investigar', '<div class="two-col">'+card('Maestría en Ciencias – Astronomía','Formación en astronomía, astrofísica, cosmología y ciencias del espacio. Integra herramientas teóricas, observacionales y de investigación.<br><br><strong>Duración estimada:</strong> 4 semestres.<br><strong>SNIES:</strong> 19901.',ma,'Programa y plan de estudios','POSGRADO')+card('Doctorado en Ciencias – Astronomía','Un camino de formación avanzada para desarrollar investigación original. Consulta con el Área Curricular las líneas, la oferta de dirección de tesis y los requisitos de la convocatoria vigente.',area,'Área Curricular de Astronomía','POSGRADO')+'</div>'+source(ma,'Maestría en Ciencias – Astronomía')+source(area,'Área Curricular de Astronomía'))
academia+=section('aspirantes','Tu ruta de ingreso','<div class="three-col">'+card('1. Explora una línea','Conoce los temas de trabajo y consulta los perfiles docentes antes de definir una propuesta.','investigacion.html','Grupos de investigación')+card('2. Revisa la convocatoria','Confirma requisitos, etapas de evaluación, calendario y documentación en el portal de admisiones.','https://admisiones.unal.edu.co/posgrado/','Admisiones de posgrado')+card('3. Contacta al programa','Para orientación sobre el proceso y asuntos curriculares, escribe a la Secretaría del OAN.','mailto:obsan_fcbog@unal.edu.co','Escribir a Secretaría')+'</div><p class="note">Fechas, cupos y requisitos dependen de cada convocatoria. La ficha enlazada desde el doctorado redirigía a la maestría en la consulta realizada; por eso se remite al Área Curricular y a la Secretaría para confirmar los detalles del doctorado.</p>')
academia+=section('estudiantes','Recursos para estudiantes','<ul class="linklist"><li>'+link('https://dninfoa.unal.edu.co/','Sistema de Información Académica — SIA')+'</li><li>'+link('https://bibliotecas.unal.edu.co/','Bibliotecas de la Universidad Nacional')+'</li><li>'+link('https://bases.unal.edu.co/','Bases de datos y recursos electrónicos')+'</li><li>'+link('https://repositorio.unal.edu.co/','Repositorio institucional: tesis y producción académica')+'</li><li><a href="laboratorios.html">Cúpulas y cuarto oscuro: conocer los laboratorios ↗</a></li><li><a href="divulgacion.html#cumulo">Cúmulo y vida estudiantil ↗</a></li></ul>')
page('academia','Aprender a explorar el universo','ACADEMIA','Formación de posgrado y recursos para una comunidad que transforma preguntas en investigación.',academia,[('programas','Programas'),('aspirantes','Aspirantes'),('estudiantes','Estudiantes')])

people=[('Benjamín Calvo Mozo','Física solar','bcalvom'),('Eduard Alexis Larrañaga Rubio','Agujeros negros; astrofísica computacional','ealarranaga'),('Giovanni Pinzón Estrada','Astrofísica estelar; astronomía y desarrollo','gapinzone'),('Jorge Enrique García Farieta','Cosmología, gravitación y simulaciones','joegarciafa'),('José Gregorio Portilla Barbosa','Galaxias activas; historia de la astronomía','jgportillab'),('José Robel Arenas Salazar','Termodinámica de agujeros negros','jrarenass'),('Juan Manuel Tejeiro Sarmiento','Cosmología','jmtejeiros'),('Leonardo Castañeda Colorado','Cosmología','lcastanedac'),('Mario Armando Higuera Garzón','Galaxias activas; historia de la astronomía','mahiguerag'),('Santiago Vargas Domínguez','Física solar, instrumentación y geomagnetismo','svargasd')]
prof='<section><p class="intro">Una comunidad docente con caminos de investigación que van del Sol y las estrellas a la gravitación y la historia de la ciencia.</p>'+source(DIR,'Directorio docente oficial del OAN')
for name,field,mail in people:prof+=f'<article class="person"><div><h3>{name}</h3><p>{field}</p></div><div><a href="mailto:{mail}@unal.edu.co">{mail}@unal.edu.co</a><br>{link(DIR,"Perfil en el directorio institucional")}</div></article>'
prof+='</section><p class="note">Los perfiles completos, la formación y las hojas de vida se consultan en el directorio oficial. La aparición en este listado reproduce la publicación institucional y no certifica disponibilidad de dirección de tesis.</p>'
page('profesores','Personas que hacen ciencia','PROFESORES','Conoce las áreas de trabajo y los canales académicos de contacto.',prof)

groups=[('Astronomía, Astrofísica y Cosmología','Creado en 1993. Sus líneas incluyen física solar, agujeros negros, cosmología, instrumentación, mecánica celeste y relatividad. La ficha institucional identifica como coordinador a Juan Manuel Tejeiro Sarmiento.','astronomia_astrofisica_y_cosmologia'),('Astronomía Galáctica, Gravitación y Cosmología','Creado en 1996. Reúne estudios de cúmulos estelares, dinámica de galaxias, lentes gravitacionales, campos magnéticos cosmológicos y teorías extendidas de gravedad. Coordinación publicada: Leonardo Castañeda Colorado.','astronomia_galactica_gravitacion_y_cosmologia'),('AGNs, Análisis Numérico y Simulación en Paralelo','Creado en 2001. Combina astronomía extragaláctica y óptica con técnicas observacionales, desarrollo de códigos y análisis numérico. Coordinación publicada: Mario Armando Higuera Garzón.','agss_analisis_numerico_y_simulacion_en_paralelo'),('Patrimonio Observatorio Astronómico Nacional','Desarrolla propuestas para conservar y dar a conocer el patrimonio material e inmaterial del OAN. Vincula astronomía e historia. Coordinación publicada: Mario Armando Higuera Garzón.','patrimonio_observatorio_astronomico_nacional')]
research='<section id="grupos"><h2>Grupos de investigación</h2><div class="two-col">'
for title,desc,slug in groups:
 url=GROUP+slug+'/'
 research+=card(title,desc,url,'Ficha institucional')
 SOURCES[url]=title
research+='</div>'+source(GROUP,'Grupos de investigación de Astronomía')+'</section>'
gosa='https://raccefyn.co/index.php/raccefyn/article/view/el-grupo-de-astrofisica-solar-gosa-del-observatorio-astronomico-'
research+=section('gosa','GoSA · Nuestra estrella como laboratorio','<div class="two-col"><div><p>El Grupo de Astrofísica Solar estudia el Sol y la relación entre sus procesos físicos y el entorno terrestre. El balance de sus primeros diez años, publicado en 2023, documenta una trayectoria de investigación y formación en Colombia.</p><p>Los campos de trabajo incluyen actividad solar, magnetismo, técnicas de observación y análisis de datos. El artículo de Santiago Vargas Domínguez, Benjamín Calvo Mozo, Juan Carlos Martínez Oliveros y Juan Camilo Buitrago Casas ofrece una entrada a esta comunidad.</p>'+source(gosa,'GoSA: diez años de investigación solar, 2023')+'</div><img src="assets/solar.jpg" alt="Sol observado por NASA SDO en ultravioleta extremo" loading="lazy"></div>')
research+=section('redes','Estrellas, datos y colaboración','<div class="two-col">'+card('Variabilidad estelar','El perfil de Giovanni Pinzón remite al proyecto ARYSOEN, dedicado a investigación estelar. VARYUN, presentado en eSPECTRA, reúne estudiantes interesados en utilizar la instrumentación del OAN.','https://sites.google.com/unal.edu.co/arysoen/main','Explorar ARYSOEN')+card('Astronomía para el desarrollo','La Oficina Andina de Astronomía para el Desarrollo es un recurso para explorar los vínculos entre educación, astronomía y desarrollo sostenible.','https://andean.astro4dev.org/','Oficina Andina')+'</div><p><a class="text-link" href="profesores.html">Consultar profesores y líneas de trabajo ↗</a></p>')
research+=section('publicaciones','Resultados que circulan','<p>La producción científica puede consultarse en las fichas de los grupos y las hojas de vida del directorio. eSPECTRA ofrece, además, una ventana a trabajos de estudiantes, artículos y reseñas de la comunidad.</p><div class="actions"><a class="button" href="espectra.html">Explorar eSPECTRA ↗</a><a class="text-link" href="medios.html">Artículos y entrevistas ↗</a></div>')
page('investigacion','Preguntas a escala del universo','INVESTIGACIÓN','Grupos, líneas y colaboraciones que conectan la observación con la teoría, el cálculo y la memoria científica.',research,[('grupos','Grupos'),('gosa','GoSA'),('redes','Colaboración'),('publicaciones','Publicaciones')])

labs='<figure><img class="wide-image" src="assets/campus.jpg" alt="Las dos cúpulas de observación astronómica en el campus de la Universidad Nacional" loading="lazy"><figcaption>Cúpulas del OAN en Ciudad Universitaria. Fotografía: Facultad de Ciencias, UNAL.</figcaption></figure>'
for id,title,desc,slug in [('grande','Cúpula grande','Un espacio para aprender a operar instrumentación astronómica y software, realizar prácticas docentes y desarrollar actividades de investigación y extensión. Su ficha de servicios incluye observaciones astronómicas e impresión 3D de piezas para instrumentación.','observacion_astronomica_cupula_grande'),('pequena','Cúpula pequeña','Laboratorio para la observación a través de telescopios y el aprendizaje de técnicas observacionales. Ofrece una conexión directa entre los conceptos de aula, el manejo del instrumento y la adquisición de datos.','observacion_astronomica_cupula_pequena'),('oscuro','Fotografía · Cuarto oscuro','La ficha institucional incluye fotografía y revelado, introducción a la espectroscopía y actividades de divulgación. Es un espacio para acercarse a la luz como portadora de información y a las técnicas con las que se registra.','fotografia_cuarto_oscuro')]:
 labs+=section(id,title,'<p>'+desc+'</p>'+source(LAB+slug+'/',title+' — ficha del laboratorio'))
labs+=section('llinas','El telescopio donado por Rodolfo Llinás','<span class="tag">INSTRUMENTACIÓN</span><p>La llegada de un telescopio reflector con espejo de 106 centímetros amplía las posibilidades de investigación y formación del OAN. La donación de Rodolfo Llinás y su instalación han sido documentadas por medios nacionales.</p><p>Para conocer el estado de puesta a punto, la disponibilidad para proyectos y los procedimientos de acceso, consulta directamente al Observatorio. La visita a las cúpulas no implica acceso libre a los equipos.</p>'+source('https://www.eltiempo.com/vida/ciencia/el-telescopio-de-rodolfo-llinas-ya-opera-en-la-universidad-nacional-asi-potenciara-la-investigacion-astronomica-3538709','EL TIEMPO: el telescopio de Rodolfo Llinás')+'<a class="button" href="servicios.html">Consultar una visita ↗</a>')
page('laboratorios','La luz se convierte en conocimiento','LABORATORIOS','Cúpulas de observación y cuarto oscuro: espacios para aprender, medir y desarrollar nuevas capacidades.',labs,[('grande','Cúpula grande'),('pequena','Cúpula pequeña'),('oscuro','Cuarto oscuro'),('llinas','Telescopio Llinás')])

services=section('visitas','Conoce las dos sedes','<p>Las visitas requieren solicitud previa. Confirma disponibilidad, tarifas, aforo y condiciones de ingreso antes de desplazarte.</p><div class="two-col">'+card('Sede histórica','Recorrido de aproximadamente 2 horas.<br><br>Martes: 8–10, 10–12 y 14–16 h.<br>Miércoles y jueves: 11–13 y 14–16 h.<br>Viernes: 14–16 h.<br><br>Solicitar con una semana de antelación y llegar 30 minutos antes.','http://tiny.cc/ServiciosOAN','Consultar disponibilidad')+card('Sede académica','Recorrido de aproximadamente 1 hora.<br><br>Viernes, en la franja de 8 a 11 h.<br><br>Ciudad Universitaria, edificio 413. Solicitar con al menos una semana de antelación.','http://tiny.cc/ServiciosOAN','Solicitar visita')+'</div>'+source(OAN,'Información institucional de visitas')+'<p class="note">Horarios publicados por el OAN al consultar las fuentes. La confirmación del equipo de servicios prevalece sobre esta información.</p>')
services+=section('domo','Domo Planetario','<p class="intro">Una experiencia de proyección astronómica para descubrir el cielo en grupo.</p><p>El Domo Planetario forma parte de la oferta divulgativa del Observatorio. Para programar una actividad educativa, informa la edad de los participantes, el tamaño del grupo, las fechas de interés y el lugar propuesto.</p><p>El equipo de servicios confirmará contenidos, duración, capacidad, condiciones de montaje, accesibilidad y costos. Estos detalles no están especificados en la página institucional consultada.</p><a class="button" href="mailto:serviciosoan_fcbog@unal.edu.co?subject=Consulta%20sobre%20el%20Domo%20Planetario">Consultar el Domo Planetario ↗</a>')
services+=section('asesoria','Conocimiento al servicio de la sociedad','<div class="three-col">'+card('Efemérides y conceptos','Cálculos de fases lunares y calendarios; certificaciones relacionadas con fenómenos astronómicos en fechas determinadas.')+card('Instrumentación e infraestructura','Asesoría en infraestructura astronómica y servicios de limpieza, reparación y mantenimiento de instrumentación óptica.')+card('Astronomía y territorio','Revisión de textos científicos, asesoría en astroturismo y proyectos sobre calidad del cielo.')+'</div><p>Las solicitudes de asesoría para entidades y empresas se tramitan con la Facultad de Ciencias. Su equipo evalúa el alcance y prepara la propuesta correspondiente.</p>'+source(base+'asesorias_y_consultorias/nuestros_servicios/empresas/observatorio_astronomico_nacional/','Servicios de asesoría del OAN')+'<a class="button" href="mailto:ayc_fcbog@unal.edu.co">Solicitar información sobre asesorías ↗</a>')
services+=section('preguntas','Antes de tu visita','<details><summary>¿Puedo asistir sin reserva?</summary><p>Solicita y espera la confirmación de la visita. El acceso a la sede histórica requiere coordinación previa.</p></details><details><summary>¿La visita incluye observación con telescopios?</summary><p>Consulta el contenido específico de la actividad. La observación depende de la programación, los equipos y las condiciones del cielo.</p></details><details><summary>¿Dónde consulto tarifas y aforos?</summary><p>En el formulario institucional de servicios y en el correo serviciosoan_fcbog@unal.edu.co. No se publican aquí valores que puedan quedar desactualizados.</p></details><details><summary>¿Cómo consulto condiciones de accesibilidad?</summary><p>Informa al equipo de servicios tus necesidades antes de confirmar la visita, para recibir orientación sobre el recorrido y las instalaciones.</p></details>')
page('servicios','Acércate al Observatorio','VISITAS Y SERVICIOS','Experiencias educativas y asesorías que conectan la astronomía con las personas y sus proyectos.',services,[('visitas','Visitas'),('domo','Domo Planetario'),('asesoria','Asesorías'),('preguntas','Preguntas frecuentes')])

out=section('cumulo','Cúmulo · El cielo nos reúne','<span class="tag">SEMILLERO</span><p class="intro">Un espacio de encuentro para estudiantes que quieren aprender y compartir astronomía, desde diferentes disciplinas.</p><p>eSPECTRA presentó Cúmulo UN en su primer número de 2023 como una iniciativa de aprendizaje colaborativo entre estudiantes de distintas sedes. El nodo Bogotá desarrolla actividades de divulgación vinculadas al Observatorio.</p><div class="two-col">'+card('Conoce sus voces','Una conversación audiovisual para descubrir el semillero, sus motivaciones y su relación con la astronomía.','https://www.youtube.com/watch?v=o7poRjRStyo','Ver conversación con Cúmulo')+card('Participa en Bogotá','Consulta las publicaciones del nodo para conocer encuentros y novedades. Confirma allí la programación de cada actividad.','https://www.threads.com/@cumulobogota','Novedades de Cúmulo Bogotá')+'</div>'+source('https://astronomiaoan.github.io/espectra/index-vol1num1.html','eSPECTRA, volumen 1, número 1 (2023)'))
out+=section('espectra','eSPECTRA · Investigar y contar','<p>Una revista que abre espacio a la producción académica, las historias de la astronomía y las voces de sus protagonistas. Explora artículos, entrevistas y reseñas en el portal editorial.</p><a class="button" href="espectra.html">Entrar a eSPECTRA ↗</a>')
out+=section('experiencias','La astronomía sale al encuentro','<div class="three-col">'+card('Domo Planetario','Proyecciones astronómicas para actividades educativas.','servicios.html#domo','Consultar el servicio')+card('Historia y memoria','Documentos y conferencias para comprender cómo se ha construido la ciencia en Colombia.','patrimonio.html','Explorar el patrimonio')+card('Astronomía en comunidad','Entrevistas que conectan la física solar, la divulgación y experiencias como Astronomía para la Paz.','https://revistapersea.com/podcast/santiago-vargas-carl-sagan-colombiano/','Escuchar en Persea')+'</div>')
out+=section('canales','Continúa explorando','<ul class="linklist"><li>'+link('https://www.youtube.com/channel/UCb1rF7m6wUC4Zhw-zsUWvLA','Canal audiovisual del Observatorio')+'</li><li>'+link('https://www.instagram.com/astronomiaoan','Instagram del OAN')+'</li><li>'+link('https://www.facebook.com/astronomiaOAN','Facebook del OAN')+'</li><li><a href="medios.html">Mediateca: entrevistas, prensa, videos y artículos ↗</a></li></ul><p class="source-note">Canales enlazados desde el portal de eSPECTRA. Las actividades antiguas se conservan como memoria, no como agenda vigente.</p>')
page('divulgacion','El universo es de todos','DIVULGACIÓN Y SEMILLEROS','Una invitación a preguntar, conversar y descubrir el cielo dentro y fuera de la universidad.',out,[('cumulo','Cúmulo'),('espectra','eSPECTRA'),('experiencias','Experiencias'),('canales','Canales')])

spec=section('revista','Una ventana a la investigación','<p class="intro">eSPECTRA reúne ciencia en formación, divulgación y memoria del Observatorio.</p><p>Su primer número apareció en 2023. La publicación da visibilidad a trabajos de estudiantes y conecta los resultados de investigación con una comunidad más amplia.</p><div class="actions"><a class="button" href="https://espectra.astronomiaoan.co/" target="_blank" rel="noopener">Abrir la revista ↗</a>'+link(SPEC+'larevista.html','Conocer el proyecto editorial')+'</div>'+source(SPEC+'oan220.html','Editorial del número inaugural'))
spec+=section('actual','Volumen 4 · Número 2 · 2026','<p>El número visible durante la consulta presenta investigaciones sobre tecnofirmas, estrellas químicamente peculiares, órbitas alrededor de agujeros negros, trazado de rayos y lentes gravitacionales.</p><div class="two-col">'+card('Huellas de Colombia en el Sistema Solar','Divulgación de Laura Daniela Jiménez Prada, integrante de Cúmulo, sobre nombres colombianos en la geografía planetaria.',SPEC+'vol4num2-divulgacion.html','Leer artículo')+card('Una conversación con Beatriz Sabogal','Trayectoria, experiencias y reflexiones de una investigadora de la astronomía colombiana.',SPEC+'vol4num2-laentrevista.html','Leer entrevista')+'</div>'+source(SPEC,'eSPECTRA: edición consultada en septiembre de 2026'))
spec+=section('archivo','Leer también es recorrer nuestra historia','<div class="two-col">'+card('El número inaugural','Una puerta de entrada a la revista, sus primeros trabajos y los semilleros presentados en 2023.','https://astronomiaoan.github.io/espectra/index-vol1num1.html','Volumen 1, número 1')+card('Antes de la torre','Alberto Gómez Gutiérrez explora los registros de Mutis y Caldas y los intercambios con Humboldt anteriores al funcionamiento del Observatorio.',SPEC+'vol2num1-ciclo220-1.html','Leer el ensayo histórico')+'</div><p>Para propuestas editoriales y consultas sobre la revista, utiliza sus canales publicados. Los números y artículos enlazados se conservan en sus plataformas originales.</p>')
page('espectra','eSPECTRA','REVISTA DEL OBSERVATORIO','Investigación, divulgación, entrevistas y memoria científica en una misma publicación.',spec,[('revista','La revista'),('actual','Edición 2026'),('archivo','Archivo')])

egr=section('comunidad','El vínculo continúa','<p class="intro">La formación en el Observatorio sigue viva en las preguntas, las clases y los proyectos de sus egresados.</p><p>Este espacio conecta a quienes cursaron sus programas con los servicios de la Universidad, la comunidad científica y las oportunidades de compartir su experiencia.</p><p>La editorial de eSPECTRA de 2023 registraba más de cien graduados entre maestría y especialización desde el inicio de la actividad de posgrado en 1999. Es una referencia histórica, no un conteo actualizado.</p>'+source(SPEC+'oan220.html','eSPECTRA: balance académico de 2023'))
egr+=section('recursos','Servicios para egresados','<div class="three-col">'+card('Programa de Egresados','Accede a los canales institucionales de vinculación y actualización.','http://egresados.unal.edu.co','Portal de Egresados UNAL')+card('Facultad de Ciencias','Consulta noticias, encuentros y oportunidades de participación de la Facultad.',base+'dependencias/egresados','Egresados de Ciencias')+card('Educación continua','Explora la oferta de cursos, diplomados y eventos de la Facultad.',base+'educacion_continua/cursos_diplomados_eventos/','Consultar la oferta')+'</div>'+source(base+'dependencias/egresados','Programa de Egresados de la Facultad de Ciencias'))
egr+=section('participa','Comparte tu trayectoria','<p>¿Te formaste en el OAN y quieres proponer una conversación, compartir una publicación o contar tu experiencia profesional? Contacta al Observatorio para explorar una participación en sus espacios académicos y de divulgación.</p><a class="button" href="mailto:obsan_fcbog@unal.edu.co?subject=Egresados%20del%20OAN%20-%20propuesta%20de%20participaci%C3%B3n">Contactar al Observatorio ↗</a><p class="note">Este portal no publica un directorio personal de egresados. Las reseñas de trayectorias podrán incorporarse con información confirmada y autorización de sus protagonistas.</p>')
page('egresados','Una comunidad que sigue creciendo','EGRESADOS','Vuelve a encontrarte con el Observatorio: conocimiento, trayectoria y nuevas conversaciones.',egr,[('comunidad','Comunidad'),('recursos','Recursos'),('participa','Participa')])

friends=section('idea','Una invitación a mirar juntos','<span class="tag">INICIATIVA EN DESARROLLO</span><p class="intro">Amigos del Observatorio propone reunir a personas que comparten la curiosidad por el universo y el interés por el patrimonio científico de Colombia.</p><p>Un punto de encuentro para ciudadanos, estudiantes, egresados, educadores y organizaciones que quieran acercarse al OAN y contribuir a la circulación del conocimiento.</p><p class="note">Esta es una propuesta de comunidad. Su estructura, las formas de vinculación y las actividades deberán ser definidas por el Observatorio. No hay membresías, cuotas, donaciones ni beneficios habilitados en este sitio.</p>')
friends+=section('caminos','Tres caminos para construir comunidad','<div class="three-col">'+card('Descubrir','Acercarse a visitas, conversaciones y contenidos de astronomía para compartir el asombro de aprender.')+card('Compartir','Proponer encuentros entre estudiantes, docentes, egresados y públicos interesados en la ciencia.')+card('Cuidar la memoria','Dar a conocer la sede histórica y contribuir, mediante iniciativas coordinadas, a valorar su patrimonio.')+'</div>')
friends+=section('contacto','¿Te interesa la iniciativa?','<p>Puedes preparar un correo al Observatorio para expresar tu interés o proponer una idea. El mensaje se abrirá en tu aplicación de correo; tú decides si enviarlo.</p><a class="button" href="mailto:obsan_fcbog@unal.edu.co?subject=Inter%C3%A9s%20en%20Amigos%20del%20Observatorio&amp;body=Hola%2C%20me%20interesa%20conocer%20el%20desarrollo%20de%20la%20iniciativa%20Amigos%20del%20Observatorio.%0A%0AMi%20propuesta%20o%20inter%C3%A9s%20es%3A%20">Preparar correo de interés ↗</a>')
page('amigos','Amigos del Observatorio','COMUNIDAD','La curiosidad nos reúne. La ciencia y su memoria nos dan un lugar de encuentro.',friends,[('idea','La idea'),('caminos','Caminos de participación'),('contacto','Contacto')])

# Pages below are extended in subsequent source files.
(ROOT/'source'/'sources-base.json').write_text(json.dumps(SOURCES,ensure_ascii=False,indent=2))
(ROOT/'source'/'footer.html').write_text(FOOT)
print('Core pages generated')
