from build_pages import *
import csv
MEM='https://www.senalmemoria.co/articulos/observatorio-astronomico-colombia'
HIST=SPEC+'vol2num1-ciclo220-2.html'
PRE=SPEC+'vol2num1-ciclo220-1.html'
FIRST='https://raccefyn.co/index.php/raccefyn/article/view/3195'
GARDEN='https://raccefyn.co/index.php/raccefyn/article/view/3583'
CAT='https://biblioteca.accefyn.org.co/cgi-bin/koha/opac-detail.pl?biblionumber=36781'
pat='<figure><img class="wide-image" src="assets/historic.jpg" alt="Sede histórica del Observatorio Astronómico Nacional, de planta octagonal" loading="lazy"><figcaption>Sede histórica, centro de Bogotá. Imagen: Viasatelital. Consulta la procedencia en Fuentes y créditos.</figcaption></figure>'
pat+=section('origen','Una torre entre la botánica y el cielo','<p class="intro">La historia del Observatorio comienza en un mundo en el que medir el cielo era también una forma de conocer el territorio.</p><p>Su origen se vincula a José Celestino Mutis y a la Real Expedición Botánica. Los estudios históricos muestran una actividad astronómica y meteorológica anterior al edificio: los registros de Mutis, los trabajos de Francisco José de Caldas y sus intercambios con Alexander von Humboldt ayudan a reconstruir ese contexto.</p><p>El trabajo de Alberto Gómez Gutiérrez invita a leer esos antecedentes a través de documentos, diarios y correspondencia. La torre no surgió de una actividad aislada, sino de una red de prácticas científicas que relacionaba observación, viajes, geografía y colecciones.</p>'+source(PRE,'Alberto Gómez Gutiérrez: antecedentes del OAN')+'<p>Construida por fray Domingo de Petrés, la sede histórica se distingue por su planta octagonal. El archivo de Señal Memoria recupera una explicación de Benjamín Calvo sobre su arquitectura y reúne imágenes del edificio dentro del paisaje del centro de Bogotá.</p>'+source(MEM,'Señal Memoria: historia y archivo audiovisual'))
timeline=[('1802–1803','Se construye el Observatorio','La obra impulsada por Mutis comienza en mayo de 1802 y concluye el 20 de agosto de 1803, en el entorno de la Expedición Botánica.',HIST),('1804','Observar para medir el tiempo','Un estudio de documentos publicado en 2025 analiza registros solares, de declinación magnética y de satélites de Júpiter de abril a septiembre de 1804.',FIRST),('1805–1806','La etapa de Caldas','Caldas se establece en Santafé a finales de 1805 y desarrolla una actividad astronómica y meteorológica sostenida desde 1806.',PRE),('Siglo XIX','Ciencia e historia republicana','El edificio atraviesa interrupciones y cambios de uso. La trayectoria de Liévano, González Benito y Garavito muestra diferentes esfuerzos por fortalecer la práctica astronómica.',HIST),('1867 / 1936','El vínculo universitario','Las fuentes distinguen la incorporación a la Universidad Nacional en 1867 y su ratificación en 1936; conviene conservar esa diferencia al narrar la historia institucional.',MEM),('1952','Una sede en Ciudad Universitaria','Se construye el observatorio del campus, ampliando los espacios para la actividad académica y observacional.',MEM),('1975','Reconocimiento patrimonial','La sede histórica es declarada Monumento Nacional. Su conservación une la arquitectura con la memoria de la ciencia.',MEM),('1999','Formación de posgrado','La editorial institucional de 2023 sitúa en 1999 el inicio de la actividad docente e investigativa de sus posgrados.',SPEC+'oan220.html'),('2023','Nace eSPECTRA','El número inaugural acompaña la conmemoración de los 220 años y abre un espacio editorial para la comunidad.',SPEC+'oan220.html'),('2025','Se recupera el jardín','El proyecto con el Jardín Botánico de Bogotá renueva el entorno vegetal y su lectura patrimonial.',GARDEN)]
pat+='<section id="cronologia"><h2>Una historia en movimiento</h2><div class="timeline">'
for date,title,txt,url in timeline:
 pat+=f'<article><time>{date}</time><div><h3>{title}</h3><p>{txt}</p><p class="source-note">{link(url,"Documento de referencia")}</p></div></article>';SOURCES[url]=title
pat+='</div></section>'
pat+=section('instrumentos','Instrumentos: otras formas de leer el pasado','<p>Un instrumento conserva algo más que una técnica de observación: permite preguntar qué se medía, cómo se aprendía a usarlo, quién lo construyó y qué resultados produjo. Estudiar esa relación entre objetos y documentos es fundamental para comprender el patrimonio astronómico.</p><div class="two-col">'+card('Relojes y cronómetros','El análisis de las observaciones de 1804 identifica registros solares asociados, presumiblemente, a determinar el adelanto o atraso de un cronómetro y un reloj de péndulo. La medición del tiempo aparece así ligada a la observación del cielo.',FIRST,'Leer el estudio documental')+card('Telescopios y mediciones','El mismo estudio analiza observaciones de satélites de Júpiter dirigidas a precisar la longitud geográfica y mediciones de declinación magnética. Los documentos permiten reconstruir prácticas, incluso cuando la atribución de sus autores sigue en discusión.',FIRST,'Consultar la investigación')+'</div><p>Para investigar telescopios, relojes, brújulas, sextantes y otras familias de instrumentación histórica, la consulta debe contrastar inventarios, inscripciones, fotografías y registros de uso. Estos ejemplos orientan la investigación; no constituyen un inventario de piezas actualmente exhibidas.</p>'+source(GROUP+'patrimonio_observatorio_astronomico_nacional/','Grupo Patrimonio OAN')+'<p class="note">Esta web no sustituye un catálogo museológico. La identificación de una pieza, su fabricante, datación, procedencia y estado de conservación deben apoyarse en su ficha documental.</p>')
pat+=section('jardin','Un patrimonio que también está vivo','<p>La restauración del jardín, planeada en 2024 y realizada en 2025, es resultado de una alianza entre el OAN y el Jardín Botánico de Bogotá. El proyecto incorporó más de 1.400 individuos vegetales, incluidos seis nuevos árboles, y recuperó la dimensión simbólica del lugar.</p><p>El diseño vincula especies asociadas a la tradición botánica con la memoria de Mutis, Humboldt y Garavito. Es una forma de conectar astronomía, paisaje cultural y educación ambiental.</p>'+source(GARDEN,'Vargas Domínguez y colaboradores: restauración del jardín, 2026'))
archive=[('Catálogo documental · 1803–1930','Registro bibliográfico de la primera parte del catálogo del Archivo Histórico del OAN. Es un punto de partida para localizar la descripción de documentos y planear una consulta.',CAT,'Registro bibliográfico'),('Catálogo documental · 1930–1949','Referencia a la segunda parte, anunciada en 2010. Amplía el recorrido documental hacia la etapa de reorganización del Observatorio.','https://godues.wordpress.com/2010/06/04/catalogo-del-archivo-historico-del-oan-ed-rac-566/','Referencia de publicación'),('ConoSer · 25 de diciembre de 1998','Entrevista con Benjamín Calvo sobre los orígenes y la arquitectura. Referencia del archivo: BTCX30 017255.',MEM,'Archivo audiovisual'),('450 años de Bogotá · 1988','Pieza sobre legado, tradición y arte que incluye al Observatorio. Referencia del archivo: UMT-200471.',MEM,'Archivo audiovisual'),('Observatorio Astronómico Nacional · Foto 1','Registro de fotografía histórica conservado en la Biblioteca Virtual del Banco de la República.','https://babel.banrepcultural.org/digital/collection/p17054coll19/id/1194/','Archivo fotográfico'),('Humboldtiana neogranadina','Colección digital para explorar los viajes y los intercambios científicos de Humboldt. El tomo III aborda cartografía y astronomía.','https://bibliotecanacional.gov.co/es-co/colecciones/biblioteca-digital/humboldtiana/Documents/index.html','Biblioteca Nacional'),('Primeras observaciones · 1804','J. Gregorio Portilla revisa registros y propone una atribución distinta de las observaciones, mostrando cómo la historia cambia al releer las fuentes.',FIRST,'Investigación histórica'),('La Casa de la Botánica','Xavier Marquínez examina el contexto botánico, educativo y museal del lugar del que surgió el Observatorio.',SPEC+'vol2num1-ciclo220-3.html','Ensayo histórico')]
pat+='<section id="archivo"><h2>Puertas de entrada al archivo</h2><p>Documentos, registros y estudios para continuar investigando. Los materiales se consultan en las instituciones que los custodian.</p>'
for title,desc,url,kind in archive:
 pat+=f'<article class="resource"><div><span class="tag">{kind}</span></div><div><h3>{title}</h3><p>{desc}</p>{link(url,"Consultar recurso")}</div></article>';SOURCES[url]=title
pat+='</section>'
pat+=section('investigar','Cómo investigar el patrimonio','<div class="three-col">'+card('Localizar','Empieza por el catálogo y registra título, fecha, autor, fondo y signatura. Un registro bibliográfico no significa que el documento esté digitalizado.')+card('Contrastar','Distingue la fecha del documento de la del acontecimiento. Compara manuscritos, publicaciones y estudios antes de atribuir una observación o una pieza.')+card('Citar y conservar','Solicita las condiciones de consulta y reproducción al custodio. Conserva la procedencia de imágenes y transcripciones para que otros puedan verificarlas.')+'</div><p>El Grupo Patrimonio OAN trabaja por el patrimonio material e inmaterial. Para consultas sobre colecciones y proyectos, utiliza el contacto publicado en su ficha.</p><a class="button" href="mailto:patrimonioOAN@gmail.com">Consultar al Grupo Patrimonio ↗</a>')
page('patrimonio','El cielo también tiene memoria','HISTORIA Y PATRIMONIO','Un recorrido por la sede histórica, sus protagonistas, los instrumentos, el jardín y los documentos que permiten volver a contar su historia.',pat,[('origen','Orígenes'),('cronologia','Cronología'),('instrumentos','Instrumentos'),('jardin','El jardín'),('archivo','Archivo'),('investigar','Investigar')])

media=[
('prensa','EL TIEMPO','2026','El telescopio de Rodolfo Llinás llega a una nueva etapa','Reportaje con declaraciones de Santiago Vargas sobre la donación, las dimensiones del instrumento y las posibilidades para la investigación.', 'https://www.eltiempo.com/vida/ciencia/el-telescopio-de-rodolfo-llinas-ya-opera-en-la-universidad-nacional-asi-potenciara-la-investigacion-astronomica-3538709'),
('video','Televisión UNAL','20 marzo 2026','Un nuevo telescopio para el Observatorio','Pieza audiovisual institucional sobre la llegada del telescopio y su relación con la formación y la investigación.','https://www.facebook.com/TelevisionUNAL/videos/-colombia-da-un-salto-hacia-las-estrellas-y-hacia-el-futuroen-el-observatorio-as/1514737633320693/'),
('video','Los Informantes · Caracol','Agosto 2026','El telescopio que Rodolfo Llinás entregó a Colombia','Reportaje audiovisual sobre la donación y su significado para la astronomía del país.','https://www.facebook.com/LosInformantesTV/videos/-el-telescopio-que-rodolfo-llin%C3%A1s-decidi%C3%B3-entregarle-a-colombia-el-reconocido-ci/1562308645591735/'),
('video','Los Informantes · Caracol','Agosto 2026','Avances de la astronomía en Colombia','Material audiovisual sobre formación e investigación astronómica.','https://www.facebook.com/LosInformantesTV/videos/los-positivos-avances-de-la-astronom%C3%ADa-en-colombia-hay-programas-de-maestr%C3%ADa-doc/1074612068393193/'),
('prensa','Radio Nacional de Colombia','26 septiembre 2022','La trayectoria de Mario Armando Higuera','Perfil de Carlos Brand que recorre su vocación y su interés por los núcleos activos de galaxias.','https://www.radionacional.co/actualidad/personajes/mario-armando-higuera-director-del-observatorio-astronomico-nacional'),
('audio','Persea · Aguacast','4 julio 2020','Conversación con Santiago Vargas','Física solar, divulgación y Astronomía para la Paz en una entrevista con Jesús y Víctor.','https://revistapersea.com/podcast/santiago-vargas-carl-sagan-colombiano/'),
('video','Canal del OAN','Fecha no confirmada','Cúmulo: voces del semillero','Conversación con participantes del semillero sobre su encuentro con la astronomía.','https://www.youtube.com/watch?v=o7poRjRStyo'),
('video','Ciclo OAN 220 años','2023','Antes del Observatorio: Mutis, Caldas y Humboldt','Conferencia de Alberto Gómez Gutiérrez citada en el ensayo histórico de eSPECTRA.','https://www.youtube.com/watch?v=DBhQu4Nlmbs'),
('archivo','Señal Memoria · ConoSer','25 diciembre 1998','Benjamín Calvo cuenta los orígenes del edificio','Entrevista conservada por RTVC, referenciada con la signatura BTCX30 017255 en su artículo de 2022.',MEM),
('archivo','Señal Memoria · Inravisión','1988','El Observatorio en la memoria audiovisual de Bogotá','Pieza de la conmemoración de los 450 años de Bogotá. Signatura UMT-200471; descrita en el artículo de Señal Memoria.',MEM),
('archivo','Banco de la República','Fecha no confirmada','La sede histórica en fotografía','Registro fotográfico que permite explorar la imagen del edificio en el archivo cultural.','https://babel.banrepcultural.org/digital/collection/p17054coll19/id/1194/'),
('articulo','eSPECTRA','2026','Entrevista con Beatriz Sabogal','Una conversación editorial sobre la trayectoria y experiencias de la investigadora.',SPEC+'vol4num2-laentrevista.html'),
('articulo','eSPECTRA','2026','Colombia en la geografía del Sistema Solar','Artículo divulgativo de Laura Daniela Jiménez Prada, integrante de Cúmulo.',SPEC+'vol4num2-divulgacion.html'),
('articulo','Revista ACCEFyN','2026','La recuperación del jardín histórico','Investigación sobre la alianza con el Jardín Botánico y la dimensión natural del patrimonio.',GARDEN),
('articulo','Revista ACCEFyN','2025','Una nueva lectura de las observaciones de 1804','J. Gregorio Portilla analiza documentos de medición del tiempo, magnetismo y posición geográfica.',FIRST),
('articulo','Revista ACCEFyN','22 junio 2023','Diez años de investigación solar con GoSA','Balance de trabajo científico y formación en el Grupo de Astrofísica Solar.',gosa),
('articulo','eSPECTRA','Ciclo 220 años','Antes de la construcción del Observatorio','Alberto Gómez Gutiérrez estudia los antecedentes meteorológicos y astronómicos.',PRE),
('articulo','eSPECTRA','Ciclo 220 años','La institución y la historia nacional','Santiago Vargas Domínguez recorre los vínculos entre el Observatorio y las transformaciones del país.',HIST),
('articulo','eSPECTRA','Ciclo 220 años','La Casa de la Botánica y su legado','Texto de Xavier Marquínez sobre el espacio que articuló botánica, educación y colecciones.',SPEC+'vol2num1-ciclo220-3.html'),
('articulo','eSPECTRA','2023','La revista como nueva etapa editorial','Mario Armando Higuera presenta el proyecto de eSPECTRA en el año de los 220 años del OAN.',SPEC+'oan220.html'),
('prensa','Agencia UNAL','7 mayo 2010','Presentación del catálogo documental','Noticia de la publicación dedicada al Archivo Histórico del Observatorio.','https://agenciadenoticias.unal.edu.co/detalle/presentan-catalogo-documental-del-observatorio-astronomico'),
('articulo','EL TIEMPO','2017','Diálogo con Javier Santaolalla','Entrevista firmada por Nicolás Bustamante y Santiago Vargas sobre ciencia y divulgación.','https://www.eltiempo.com/vida/ciencia/javier-santaolalla-en-colombia-entrevista-con-el-cientifico-y-divulgador-120160')]
(ROOT/'source'/'media.json').write_text(json.dumps(media,ensure_ascii=False,indent=2))
labels={'prensa':'Prensa','audio':'Audio','video':'Video','articulo':'Artículo','archivo':'Archivo'}
med='<section><p class="intro">Voces, textos e imágenes que cuentan la investigación y la vida del Observatorio.</p><p>Una selección documentada de participaciones y recursos localizados en fuentes públicas. Incluye producción propia, entrevistas externas y archivo histórico; no representa un inventario exhaustivo de todas las apariciones.</p><label class="search-label" for="media-search">Buscar por persona, tema o medio</label><input id="media-search" class="search" type="search" placeholder="Por ejemplo: Calvo, telescopio, Cúmulo…"><div class="filter-bar" aria-label="Filtrar recursos por formato"><button data-filter="todos" aria-pressed="true">Todos</button>'+''.join(f'<button data-filter="{k}" aria-pressed="false">{v}</button>' for k,v in labels.items())+'</div><p id="media-count" role="status" aria-live="polite"></p><div class="empty">No se encontraron recursos con esos criterios. Prueba otra palabra o selecciona Todos.</div>'
for kind,publisher,date,title,desc,url in media:
 med+=f'<article class="resource" data-media="{kind}"><div><span class="tag">{labels[kind]}</span><small>{date}</small></div><div><small>{publisher}</small><h3>{title}</h3><p>{desc}</p>{link(url,"Consultar en la fuente")}</div></article>';SOURCES[url]=title+' — '+publisher
med+='</section><section class="inset"><h2>Más conversaciones, más miradas</h2><p>El canal del Observatorio conserva charlas y otros contenidos audiovisuales. Consulta su catálogo para seguir explorando.</p>'+link('https://www.youtube.com/channel/UCb1rF7m6wUC4Zhw-zsUWvLA','Canal de YouTube del OAN')+'<p class="source-note">Los videos y audios se abren en su plataforma original. Algunos sitios pueden requerir iniciar sesión, aceptar cookies o una suscripción. Las fechas no confirmadas se indican expresamente.</p></section>'
page('medios','Voces del Observatorio','MEDIATECA Y PRENSA','Entrevistas, reportajes, artículos y archivo para conocer la ciencia desde sus protagonistas.',med)

credits=section('criterios','Información con procedencia','<p>Portal elaborado a partir de fuentes institucionales del OAN y la Facultad de Ciencias, eSPECTRA, publicaciones científicas, archivos culturales y medios. Fecha de consulta: <strong>16 de septiembre de 2026</strong>.</p><p>Se presentan síntesis editoriales y enlaces para ampliar la lectura. El archivo de medios es una selección abierta a ampliación. Las fechas de los documentos y las de su publicación se distinguen cuando están disponibles.</p><p>Las fuentes pueden contener errores de plantilla, enlaces antiguos y diferencias históricas. No se trasladaron cupos de convocatorias sin contexto, fechas de eventos pasados como agenda actual ni textos ajenos al área. Los detalles operativos se remiten a los canales oficiales.</p>')
credits+=section('imagenes','Créditos de imágenes','<div class="table-scroll"><table><thead><tr><th>Imagen</th><th>Procedencia</th><th>Uso y atribución</th></tr></thead><tbody><tr><td>Sede histórica</td><td>'+link('https://viasatelital.com/mapas/bogota_observatorio_astronomico.php','Viasatelital')+'</td><td>Fotografía encontrada en esa página. No se localizó una licencia de reutilización expresa; validar autorización antes de la publicación institucional.</td></tr><tr><td>Cúpulas del campus</td><td>'+link(base+'asesorias_y_consultorias/nuestros_servicios/empresas/observatorio_astronomico_nacional/','Facultad de Ciencias, UNAL')+'</td><td>Fotografía institucional OAN-14. El portal indica algunos derechos reservados; confirmar el crédito y uso institucional.</td></tr><tr><td>Sol en ultravioleta</td><td>'+link('https://svs.gsfc.nasa.gov/14589/','NASA / SDO')+'</td><td>Observación del evento solar del 10–11 de mayo de 2024. Colores asociados a longitudes de onda ultravioleta; no es una imagen en tiempo real.</td></tr></tbody></table></div>')
credits+='<section id="fuentes"><h2>Fuentes consultadas y recursos</h2><ol class="linklist">'
for url,title in SOURCES.items():credits+='<li>'+link(url,e(title))+'</li>'
credits+='</ol></section>'
credits+=section('alcance','Alcance de esta propuesta','<p>Amigos del Observatorio se presenta como iniciativa en desarrollo. Los enlaces de contacto preparan mensajes en la aplicación de correo del visitante; no realizan inscripciones, reservas o pagos automáticos.</p><p>Los contenidos, la identidad visual y los datos deben pasar por revisión institucional antes de reemplazar el portal oficial. Esta versión no afirma aprobación ni representación administrativa.</p>')
page('fuentes','Fuentes y créditos','DOCUMENTACIÓN','Consulta la procedencia de la información, las imágenes y los recursos de este portal.',credits,[('criterios','Criterios'),('imagenes','Imágenes'),('fuentes','Bibliografía'),('alcance','Alcance')])
with (D/'fuentes.csv').open('w',newline='') as f:
 w=csv.writer(f);w.writerow(['recurso','url','consulta']);w.writerows((title,url,'2026-09-16') for url,title in SOURCES.items())
with (D/'mediateca.csv').open('w',newline='') as f:
 w=csv.writer(f);w.writerow(['formato','medio','fecha','titulo_editorial','descripcion','url']);w.writerows(media)
(ROOT/'source'/'sources.json').write_text(json.dumps(SOURCES,ensure_ascii=False,indent=2))
print('Archive, media and credits generated:',len(media),'media entries,',len(SOURCES),'sources')
