from pathlib import Path
import json,re,html,csv
ROOT=Path(__file__).resolve().parents[1];D=ROOT/'dist';S=ROOT/'source'
base=json.loads((S/'es-segments.json').read_text());M={}
for line in (S/'en-translations.txt').read_text().splitlines():
 i,t=line.split('|',1);M[base[int(i)]]=t
extra={}
def tx(es,en):extra[es]=en;return es
def link(u,t):return f'<a href="{html.escape(u,quote=True)}" target="_blank" rel="noopener">{t} ↗</a>'
channel='https://www.youtube.com/@astronomiaoan'
service='https://ciencias.bogota.unal.edu.co/asesorias_y_consultorias/nuestros_servicios/empresas/observatorio_astronomico_nacional/'
launch='https://es.linkedin.com/posts/santiago-vargas-7a86238a_juevesbajolasestrellas-activity-7456814038488924160-Rqlm'
report='https://periodico.unal.edu.co/articulos/cientificos-de-la-unal-apuestan-por-ir-mas-alla-de-la-luna-y-descifrar-secretos-profundos-del-universo'
television='https://www.youtube.com/watch?v=jD9NjuPwP3A'
# Existing HTML is the canonical source; this extension preserves its sections.
home=(D/'index.html').read_text();head=home.split('<main')[0];head=re.sub(r'<div class="new-tabs">.*?</nav></div>','',head);head=re.sub(r'<link rel="alternate"[^>]+>','',head);foot=home[home.index('<footer'):]
def page(filename,title,kicker,intro,body):
 h=re.sub(r'<title>.*?</title>',f'<title>{title} · OAN Colombia</title>',head)
 extra[title+' · OAN Colombia']=extra.get(title,title)+' · OAN Colombia'
 s=h+f'<main id="contenido"><div class="page-hero"><div class="breadcrumb"><a href="index.html">Inicio</a> / <span>{title}</span></div><p class="eyebrow">{kicker}</p><h1>{title}</h1><p>{intro}</p></div><div class="content">{body}</div></main>'+foot
 (D/filename).write_text(s)
v=json.loads((S/'youtube-extracted.json').read_text())
selected=[0,2,3,5,6,9,11,12,13,14,17,18,21,23,24,25,26,27,28]
titles=['Under the skies of San Pedro Mártir','The great encounter: the Venus–Jupiter conjunction','Engineering in asteroid detection','An adventure through the universe: a travelling museum experience from the Museum of Science and Play','The Luis Ángel Arango Library, one click away','Thursdays under the Stars: IsleIA, the Observatory’s new AI agent','Are we looking up? Asteroids: science, risk and perception','Secrets of space photography on the Artemis II mission','Returning to the Moon','Chilean skies: a journey through the universe from some of the planet’s most pristine skies','Supermassive black holes and other mysteries','Measuring the geomagnetic field from Colombia','Space weather and space exploration','Camille Flammarion and his legacy in Colombia','Terrestrial endolithic pigments: could they exist on Mars?','Echoes from beyond','Reconstructing a historic garden','Beyond the atmosphere: the challenge of space law','Colombia on the Moon: from research to exploration']
catalog=[]
for i,en in zip(selected,titles):
 a=v[i].copy();a['title_en']=en;a['date']=a['date'][:10];a['url']='https://www.youtube.com/watch?v='+a['id'];a['image']='assets/talks/'+a['id']+'.jpg';a['date_type']='YouTube publication date';a['source']=a['url'];a['reviewed']='2026-09-24';catalog.append(a)
json.dump(catalog,(S/'conferencias.json').open('w'),ensure_ascii=False,indent=2)
json.dump(catalog,(D/'conferencias.json').open('w'),ensure_ascii=False,indent=2)
with (D/'conferencias.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=['id','title','title_en','date','date_type','description','url']);w.writeheader();w.writerows({k:a[k] for k in w.fieldnames} for a in catalog)
cards=''
for a in catalog:
 title=tx(html.escape(a['title']),html.escape(a['title_en']));desc=a['description'].strip();eng=re.sub(r'^Invitados?:\s*','Guests: ',desc);eng=re.sub(r'^Invitada:\s*','Guest: ',eng);eng=re.sub(r'^Con ','With ',eng);eng=eng.replace('Profesor Adjunto del OAN','OAN Adjunct Professor').replace('Personal de apoyo de la Biblioteca Luis Angel Arango','Luis Ángel Arango Library support staff').replace('Jardín Botánico de Bogotá','Bogotá Botanical Garden')
 desc=tx(html.escape(desc),html.escape(eng));duration=int(a['duration']);dur=f'{duration//3600}:{duration%3600//60:02}:{duration%60:02}' if duration>=3600 else f'{duration//60}:{duration%60:02}'
 cards+=f'<article class="talk-card" data-talk data-year="{a["date"][:4]}"><a class="talk-image" href="{a["url"]}" target="_blank" rel="noopener"><img src="{a["image"]}" alt="{html.escape(a["title"],quote=True)}" loading="lazy" width="480" height="360"><span class="play" aria-hidden="true">▶</span><span class="duration">{dur}</span></a><div class="talk-copy"><p class="eyebrow">{tx("PUBLICACIÓN","PUBLISHED")} · <time datetime="{a["date"]}">{a["date"]}</time></p><h3>{title}</h3><p>{desc}</p>{link(a["url"],tx("Ver conferencia","Watch the talk"))}</div></article>'
body=f'''<section class="two-col"><div><h2>{tx('Una cita con el universo','A date with the universe')}</h2><p>{tx('Jueves bajo las estrellas es el ciclo de charlas divulgativas del Observatorio. Sus encuentros acercan la astronomía al público y pueden complementarse con observación por telescopio cuando el tiempo lo permite.','Thursdays under the Stars is the Observatory’s public lecture series. Its meetings bring astronomy to a wider audience and may include telescope observing when weather permits.')}</p><p>{tx('La información institucional anuncia las charlas los jueves a las 6:30 p. m. en el auditorio del OAN, en Bogotá. Confirma cada sesión en los canales oficiales antes de asistir.','Institutional information lists talks on Thursdays at 6:30 p.m. at the OAN auditorium in Bogotá. Confirm each session through the official channels before attending.')}</p><p class="source-note">Fuente: {link(service,'Facultad de Ciencias, UNAL')}</p></div><aside class="card"><span class="tag">{tx('ENCUENTROS Y TRANSMISIONES','MEETINGS & STREAMS')}</span><h3>{tx('El Observatorio en YouTube','The Observatory on YouTube')}</h3><p>{tx('Explora las transmisiones, suscríbete al canal y consulta nuevas conferencias directamente en @astronomiaoan.','Explore streams, subscribe to the channel and find new talks directly at @astronomiaoan.')}</p><div class="actions">{link(channel,tx('Abrir canal oficial','Open the official channel'))}{link(channel+'/streams',tx('Todas las transmisiones','All streams'))}</div></aside></section>
<section id="biblioteca"><p class="eyebrow">{tx('BIBLIOTECA DE CONFERENCIAS','TALK LIBRARY')}</p><h2>{tx('Una charla. Una nueva perspectiva.','One talk. A new perspective.')}</h2><p>{tx('Selección de 19 conferencias del canal oficial, con las miniaturas publicadas por el Observatorio. Busca por título o invitado y filtra por año. Las fechas corresponden a la publicación en YouTube, que puede ser posterior a la charla.','A selection of 19 talks from the official channel, with thumbnails published by the Observatory. Search by title or guest and filter by year. Dates refer to YouTube publication, which may be later than the talk itself.')}</p><label for="talk-search" class="search-label">{tx('Buscar una conferencia o un invitado','Search for a talk or guest')}</label><input id="talk-search" type="search" class="search" placeholder="{tx('IsleIA, Luna, asteroides…','IsleIA, Moon, asteroids…')}"><div class="filter-bar" aria-label="{tx('Filtrar por año','Filter by year')}"><button data-year-filter="all" aria-pressed="true">Todos</button><button data-year-filter="2026" aria-pressed="false">2026</button><button data-year-filter="2025" aria-pressed="false">2025</button></div><p id="talk-count" role="status" aria-live="polite"></p><div class="talk-grid">{cards}</div><p id="talk-empty" hidden>{tx('No hay conferencias que coincidan. Prueba otro título, invitado o año.','No matching talks. Try another title, guest or year.')}</p><p class="source-note">{tx('Catálogo consultado el 24 de septiembre de 2026. Los videos se abren en YouTube y conservan su idioma original.','Catalogue consulted on September 24, 2026. Videos open on YouTube and retain their original language.')}</p><div class="actions"><a class="text-link" href="conferencias.csv" download>{tx('Descargar catálogo CSV','Download the CSV catalogue')} ↓</a><a class="text-link" href="conferencias.json" download>{tx('Descargar metadatos JSON','Download JSON metadata')} ↓</a></div></section>'''
page('jueves.html',tx('Jueves bajo las estrellas','Thursdays under the Stars'),tx('CONVERSACIONES PARA MIRAR MÁS LEJOS','CONVERSATIONS THAT TAKE US FURTHER'),tx('Astronomía, preguntas y encuentros. Una biblioteca para volver a las voces que nos acercan al universo.','Astronomy, questions and encounters. A library to revisit the voices that bring the universe closer.'),body)
body=f'''<section class="isle-intro"><div><p class="eyebrow">{tx('ASTRONOMÍA + DATOS + INTELIGENCIA ARTIFICIAL','ASTRONOMY + DATA + ARTIFICIAL INTELLIGENCE')}</p><h2>{tx('Nuevas conexiones para el conocimiento.','New connections for knowledge.')}</h2><p class="intro">{tx('IsleIA es el agente de inteligencia artificial del Observatorio Astronómico Nacional de Colombia. Su presentación pública en Jueves bajo las estrellas fue anunciada para el 7 de mayo de 2026.','IsleIA is the artificial intelligence agent of Colombia’s National Astronomical Observatory. Its public presentation at Thursdays under the Stars was announced for May 7, 2026.')}</p><p>{tx('El proyecto conecta astronomía, datos y tecnología para explorar información. UNAL Periódico lo describe como un desarrollo con estudiantes de pregrado, maestría y doctorado que busca conectar décadas de producción científica.','The project connects astronomy, data and technology to explore information. UNAL Periódico describes it as a development involving undergraduate, master’s and doctoral students, intended to connect decades of scientific output.')}</p><p class="source-note">{link(launch,tx('Anuncio de Santiago Vargas','Announcement by Santiago Vargas'))} · {link(report,'UNAL Periódico')}</p></div><div class="isle-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><strong>Isle<span>IA</span></strong><small>OAN · 2026</small></div></section>
<section><h2>{tx('Explorar la memoria académica','Exploring academic knowledge')}</h2><div class="three-col"><article class="card"><span class="index">01</span><h3>{tx('Encontrar información','Find information')}</h3><p>{tx('La pieza de divulgación de Televisión UNAL presenta la posibilidad de explorar veinte años de tesis del Observatorio.','A Televisión UNAL outreach video presents the ability to explore twenty years of Observatory theses.')}</p></article><article class="card"><span class="index">02</span><h3>{tx('Conectar investigaciones','Connect research')}</h3><p>{tx('Una forma de acercarse a relaciones entre trabajos y al conocimiento acumulado por la comunidad académica.','A way to explore relationships between research projects and knowledge accumulated by the academic community.')}</p></article><article class="card"><span class="index">03</span><h3>{tx('Conocer el proyecto','Discover the project')}</h3><p>{tx('La conferencia de presentación permite escuchar al equipo y conocer la iniciativa en sus propias palabras.','The presentation lecture offers an opportunity to hear the team describe the initiative in their own words.')}</p></article></div><p class="source-note">{link(television,'Televisión UNAL')} · {link(report,'UNAL Periódico')}</p></section>
<section class="two-col"><article class="image-card"><a href="https://www.youtube.com/watch?v=Syagimzi1Xw" target="_blank" rel="noopener"><img src="assets/talks/Syagimzi1Xw.jpg" alt="{tx('Presentación de IsleIA en el canal del Observatorio','IsleIA presentation on the Observatory channel')}" loading="lazy"></a><div><span class="tag">{tx('PRESENTACIÓN · 7 MAYO 2026','PRESENTATION · MAY 7, 2026')}</span><h3>{tx('Conoce IsleIA desde su lanzamiento','Discover IsleIA through its launch')}</h3><p>{tx('La descripción de la grabación identifica como invitados a Johnatan Bernal, Hernán Guerrero, Joar Buitrago, Juan Esteban Agudelo y Santiago Vargas.','The recording’s description lists Johnatan Bernal, Hernán Guerrero, Joar Buitrago, Juan Esteban Agudelo and Santiago Vargas as guests.')}</p>{link('https://www.youtube.com/watch?v=Syagimzi1Xw',tx('Ver la presentación completa','Watch the full presentation'))}</div></article><article class="card"><p class="eyebrow">{tx('INFORMACIÓN Y ACCESO','INFORMATION & ACCESS')}</p><h3>{tx('Consulta al Observatorio','Contact the Observatory')}</h3><p>{tx('Las fuentes consultadas describen IsleIA, pero no permitieron confirmar una dirección pública de acceso al agente. Para conocer su disponibilidad y condiciones de uso, contacta al OAN.','The sources consulted describe IsleIA, but did not establish a public access URL for the agent. Contact the OAN about availability and conditions of use.')}</p><a class="button" href="mailto:obsan_fcbog@unal.edu.co?subject=IsleIA">{tx('Consultar sobre IsleIA','Enquire about IsleIA')} ↗</a><p class="source-note">{tx('Esta página reúne información y grabaciones del proyecto; no es una interfaz de conversación con IsleIA.','This page brings together information and recordings about the project; it is not an IsleIA chat interface.')}</p><hr><h3>{tx('Más conversaciones sobre el universo','More conversations about the universe')}</h3><a href="jueves.html">{tx('Explorar Jueves bajo las estrellas','Explore Thursdays under the Stars')} ↗</a></article></section>'''
page('isleia.html','IsleIA',tx('LA INTELIGENCIA ARTIFICIAL DEL OBSERVATORIO','THE OBSERVATORY’S ARTIFICIAL INTELLIGENCE'),tx('Una iniciativa para explorar información, conectar investigaciones y acercarnos a la producción científica del OAN.','An initiative to explore information, connect research and engage with the OAN’s scientific output.'),body)
# Add navigation to every Spanish page, and point older homepage/outreach links to the new pages.
for p in D.glob('*.html'):
 s=p.read_text();s=re.sub(r'<div class="new-tabs">.*?</nav></div>','',s);s=re.sub(r'<link rel="alternate"[^>]+>','',s)
 if 'class="new-tabs"' not in s:
  s=s.replace('<main', '<div class="new-tabs"><a href="jueves.html">Jueves bajo las estrellas</a><a href="isleia.html">IsleIA</a><nav class="language-switch" aria-label="Idioma"><a lang="es" href="'+p.name+'" aria-current="true">ES</a><a lang="en" href="en/'+p.name+'">EN</a></nav></div><main',1)
 s=s.replace('https://www.youtube.com/channel/UCb1rF7m6wUC4Zhw-zsUWvLA',channel)
 s=s.replace('Propuesta de portal · Información consultada el 16 de septiembre de 2026.','Propuesta de portal · Base documental: 16 de septiembre de 2026. Actualización bilingüe, Jueves e IsleIA: 24 de septiembre de 2026.')
 p.write_text(s)
extra['Propuesta de portal · Base documental: 16 de septiembre de 2026. Actualización bilingüe, Jueves e IsleIA: 24 de septiembre de 2026.']='Proposed portal · Core sources: September 16, 2026. Bilingual, talks and IsleIA update: September 24, 2026.'
M.update(extra)
for k,v in extra.items():
 M[k+' ↗']=v+' ↗';M[k+' ↓']=v+' ↓'
M.update(json.loads((S/'additional-translations.json').read_text()))
# Text and accessible attributes are translated while proper names and citations stay identifiable.
attrs={'Observatorio Astronómico Nacional, inicio':'National Astronomical Observatory, home','Conoce el Observatorio Astronómico Nacional de Colombia: investigación, formación, patrimonio, divulgación y servicios.':'Explore Colombia’s National Astronomical Observatory: research, education, heritage, outreach and services.','Torre octagonal de la sede histórica del Observatorio en Bogotá':'Octagonal tower of the historic Observatory in Bogotá','Cúpulas de la sede del Observatorio en la Ciudad Universitaria':'Observatory domes on the university campus','Imagen del Sol en ultravioleta extremo obtenida por el observatorio espacial SDO de NASA':'Extreme ultraviolet image of the Sun from NASA’s Solar Dynamics Observatory','Idioma':'Language'}
for a in catalog:attrs[html.escape(a['title'],quote=True)]=html.escape(a['title_en'],quote=True)
attrs.update(extra)
attrs.update({'Por ejemplo: Calvo, telescopio, Cúmulo…':'For example: Calvo, telescope, Cúmulo…','Filtrar recursos por formato':'Filter resources by format','Las dos cúpulas de observación astronómica en el campus de la Universidad Nacional':'The two astronomical observation domes on the Universidad Nacional campus','Sede histórica del Observatorio Astronómico Nacional, de planta octagonal':'The octagonal historic building of the National Astronomical Observatory','Sol observado por NASA SDO en ultravioleta extremo':'The Sun observed in extreme ultraviolet by NASA SDO'})
(D/'en').mkdir(exist_ok=True)
for p in D.glob('*.html'):
 s=p.read_text();parts=re.split(r'(<[^>]+>)',s)
 for i,t in enumerate(parts):
  if not t.startswith('<'):parts[i]=M.get(t,t)
 s=''.join(parts).replace('<html lang="es">','<html lang="en">')
 def attr(m):
  k,val=m.group(1),m.group(2);return f'{k}="{attrs.get(val,M.get(val,val))}"'
 s=re.sub(r'(alt|aria-label|placeholder|content)="([^"]*)"',attr,s)
 s=s.replace('href="assets/','href="../assets/').replace('src="assets/','src="../assets/')
 s=s.replace('href="conferencias.','href="../conferencias.').replace('href="fuentes.csv','href="../fuentes.csv').replace('href="mediateca.csv','href="../mediateca.csv')
 s=s.replace(f'lang="es" href="{p.name}" aria-current="true"',f'lang="es" href="../{p.name}"').replace(f'lang="en" href="en/{p.name}"',f'lang="en" href="{p.name}" aria-current="true"')
 s=s.replace('</head>',f'<link rel="alternate" hreflang="es" href="../{p.name}"><link rel="alternate" hreflang="en" href="{p.name}"></head>')
 (D/'en'/p.name).write_text(s)
 es=p.read_text();es=es.replace('</head>',f'<link rel="alternate" hreflang="es" href="{p.name}"><link rel="alternate" hreflang="en" href="en/{p.name}"></head>');p.write_text(es)
json.dump(M,(S/'translations-en.json').open('w'),ensure_ascii=False,indent=2)
print('Built 15 pages in each language and',len(catalog),'talk cards.')
# Keep the requested navigation placement when regenerating language pages.
import runpy
runpy.run_path(str(S/'move_navigation.py'))
runpy.run_path(str(S/'refine_isleia.py'))
runpy.run_path(str(S/'final_visual_updates.py'))
runpy.run_path(str(S/'fix_video_referrer.py'))
