from pathlib import Path
import re
R=Path(__file__).resolve().parents[1];D=R/'dist'
VIDEO='https://www.tiktok.com/@televisionunal/video/7679463096548691208'
for p in D.rglob('*.html'):
 s=p.read_text().replace('IsleIA','isleIA').replace('Isle<span>IA','isle<span>IA');en=p.parent.name=='en'
 if 'class="brand-name"' not in s:
  label='National<br>Astronomical Observatory' if en else 'Observatorio<br>Astronómico Nacional'
  s=re.sub(r'(<img class="brand-logo"[^>]*>)',lambda m:m[1]+'<span class="brand-name">'+label+'</span>',s,count=1)
 # Remove the requested UNAL Periódico article from visible source lists too.
 s=re.sub(r'<li><a href="https://periodico.unal.edu.co/articulos/cientificos-de-la-unal-apuestan-por-ir-mas-alla-de-la-luna-y-descifrar-secretos-profundos-del-universo"[^>]*>.*?</a></li>','',s)
 if p.name=='isleia.html':
  pre=s.split('<main')[0];foot=s[s.index('<footer'):];prefix='../' if en else ''
  if en:
   kicker='THE OBSERVATORY’S ARTIFICIAL INTELLIGENCE';intro='More than twenty years of science, connected through artificial intelligence.'
   heading='An agent for exploring knowledge';description='isleIA is the first artificial intelligence agent developed by Universidad Nacional de Colombia (UNAL), created at its National Astronomical Observatory (OAN).'
   detail='Driven by faculty and undergraduate, master’s and doctoral students, the project was officially presented in May 2026. Its main goal is to digitize and connect more than twenty years of the Observatory’s scientific output, theses and historical records.'
   features=[('Fast literature reviews','Helps researchers cross-reference complex information and find scientific background or methods from specific theses, including solar astrophysics, in seconds.'),('Mathematical understanding','Interprets direct questions about formulas and mathematical expressions contained in documents.'),('Research trends','Helps identify how astronomical research methods have evolved over recent decades.'),('Administrative support','Supports the organization and consultation of documents in the institution’s historical archive, alongside its academic uses.')]
   feat_title='What can isleIA help with?';watch='Discover isleIA in action';watchintro='Watch this Televisión UNAL report to learn how the tool works and how it can support academic research.';fallback='Watch the report on TikTok';note='The embedded video is provided by TikTok. If playback is unavailable in your browser, open the original report.';launch='Revisit the launch';launchtext='The May 7, 2026 presentation at Thursdays under the Stars brings together the team and introduces the initiative.';launchlink='Watch the full presentation';contact='Information and access';contacttext='Contact the Observatory to ask about access to isleIA, its availability and conditions of use.';contactlink='Enquire about isleIA';home='Home';source='Report: Televisión UNAL';video_title='Televisión UNAL report about isleIA';faq='This page presents the project and its videos; it is not an isleIA chat interface.'
  else:
   kicker='LA INTELIGENCIA ARTIFICIAL DEL OBSERVATORIO';intro='Más de veinte años de ciencia, conectados mediante inteligencia artificial.'
   heading='Un agente para explorar el conocimiento';description='isleIA es el primer agente de inteligencia artificial desarrollado por la Universidad Nacional de Colombia (UNAL), creado específicamente en el Observatorio Astronómico Nacional (OAN).'
   detail='Impulsado por docentes y estudiantes de pregrado, maestría y doctorado, el proyecto fue presentado oficialmente en mayo de 2026. Su principal objetivo es digitalizar y conectar más de veinte años de producción científica, tesis de grado y archivos históricos del Observatorio.'
   features=[('Revisiones bibliográficas veloces','Permite a los investigadores cruzar información compleja y encontrar en segundos antecedentes científicos o metodologías de tesis específicas, por ejemplo, en astrofísica solar.'),('Comprensión matemática','Puede interpretar preguntas directas sobre fórmulas o expresiones matemáticas contenidas en los documentos.'),('Análisis de tendencias','Ayuda a identificar cómo han evolucionado los métodos de investigación astronómica en las últimas décadas.'),('Gestión administrativa','Además de sus usos académicos, apoya la organización y consulta de la documentación del archivo histórico de la institución.')]
   feat_title='¿En qué puede ayudar isleIA?';watch='Conoce isleIA en acción';watchintro='Descubre cómo funciona la herramienta y su impacto académico en este informe de Televisión UNAL.';fallback='Ver el informe en TikTok';note='El video embebido es proporcionado por TikTok. Si tu navegador no permite reproducirlo, abre el informe original.';launch='Vuelve a su presentación';launchtext='La presentación del 7 de mayo de 2026 en Jueves bajo las estrellas reúne al equipo y permite conocer la iniciativa desde su lanzamiento.';launchlink='Ver la presentación completa';contact='Información y acceso';contacttext='Contacta al Observatorio para consultar el acceso a isleIA, su disponibilidad y las condiciones de uso.';contactlink='Consultar sobre isleIA';home='Inicio';source='Informe: Televisión UNAL';video_title='Informe de Televisión UNAL sobre isleIA';faq='Esta página presenta el proyecto y sus videos; no es una interfaz de conversación con isleIA.'
  cards=''.join(f'<article class="card"><span class="index">0{i}</span><h3>{t}</h3><p>{v}</p></article>' for i,(t,v) in enumerate(features,1))
  s=pre+f'''<main id="contenido"><div class="page-hero"><div class="breadcrumb"><a href="index.html">{home}</a> / isleIA</div><p class="eyebrow">{kicker}</p><h1>isleIA</h1><p>{intro}</p></div><div class="content"><section class="isle-intro"><div><h2>{heading}</h2><p class="intro">{description}</p><p>{detail}</p><p class="source-note"><a href="{VIDEO}" target="_blank" rel="noopener">{source} ↗</a></p></div><div class="isle-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="orbit orbit-three"></div><strong>isle<span>IA</span></strong><small>OAN · 2026</small></div></section><section><h2>{feat_title}</h2><div class="two-col">{cards}</div></section><section id="video" class="isle-video-section"><div><p class="eyebrow">TELEVISIÓN UNAL</p><h2>{watch}</h2><p>{watchintro}</p><a class="text-link" href="{VIDEO}" target="_blank" rel="noopener">{fallback} ↗</a><p class="source-note">{note}</p></div><div class="tiktok-frame"><iframe src="https://www.tiktok.com/player/v1/7679463096548691208?autoplay=0" title="{video_title}" loading="lazy" allow="fullscreen; picture-in-picture; encrypted-media" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div></section><section class="two-col"><article class="image-card"><a href="https://www.youtube.com/watch?v=Syagimzi1Xw" target="_blank" rel="noopener"><img src="{prefix}assets/talks/Syagimzi1Xw.jpg" alt="isleIA · 2026-05-07" loading="lazy"></a><div><h3>{launch}</h3><p>{launchtext}</p><a href="https://www.youtube.com/watch?v=Syagimzi1Xw" target="_blank" rel="noopener">{launchlink} ↗</a></div></article><article class="card"><h3>{contact}</h3><p>{contacttext}</p><a class="button" href="mailto:obsan_fcbog@unal.edu.co?subject=isleIA">{contactlink} ↗</a><p class="source-note">{faq}</p></article></section></div></main>'''+foot
 p.write_text(s)
# Use the requested spelling in exported catalogues as well.
for ext in ('*.json','*.csv'):
 for p in D.glob(ext):p.write_text(p.read_text().replace('IsleIA','isleIA'))
